project_id = "zzulxowwlqndtrlmfnij"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[auth.email]
enabled = true
port = 54327
smtp_admin_email = "admin@example.com"
smtp_host = "localhost"
smtp_port = 2500
smtp_user = "admin@example.com"
smtp_pass = "password"

[functions]
enabled = true
port = 54328

[functions.session-manager]
verify_jwt = true

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true