// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzulxowwlqndtrlmfnij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6dWx4b3d3bHFuZHRybG1mbmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDgxNjcsImV4cCI6MjA2ODIyNDE2N30.WWaJuOHtzSJoFuIdWJIjxNmq7il7I7bFkx04Wlgi-MU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});